### ISSUE TITLE
[question]May I ask questions for device tree?

### ISSUE THREAD

**Issue by skysumbra** [mohammad92/android_device_samsung_dm3q#1]
I want to generate device tree for pixel 7 phone, but i get some question of content.
I was found this [Vendor_Boot ROMs](https://forum.xda-developers.com/t/vendor_boot-roms.4575777/) webpage on XDA forum,
maybe device is vendor_boot-as-recovery structure.

May i ask questions for device tree?
thank you.

**Comment by mohammad92** [comment]
Sorry, Im Samsung guy
